# Generated by Django 4.2.10 on 2025-04-04 13:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0002_alter_itinerary_description_alter_itinerary_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pointofinterest',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Fácil'), ('MEDIUM', 'Medio'), ('HARD', 'Difícil')], max_length=20),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='estimated_time',
            field=models.DurationField(),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='pointofinterest',
            name='type',
            field=models.CharField(choices=[('MONUMENT', 'Monumento'), ('MUSEUM', 'Museo'), ('PARK', 'Parque'), ('BEACH', 'Playa'), ('VIEWPOINT', 'Mirador'), ('OTHER', 'Otro')], max_length=50),
        ),
    ]
