[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
DJANGO_DEBUG = "False"
RAILWAY_ENVIRONMENT = "True"
PYTHONUNBUFFERED = "1" 