[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "./start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
DJANGO_DEBUG = "False"
RAILWAY_ENVIRONMENT = "True"
DATABASE_HOST = "RAILWAY_POSTGRESQL_HOST"
DATABASE_PORT = "RAILWAY_POSTGRESQL_PORT"
DATABASE_USER = "RAILWAY_POSTGRESQL_USER"
DATABASE_PASSWORD = "RAILWAY_POSTGRESQL_PASSWORD"
DATABASE_NAME = "RAILWAY_POSTGRESQL_DATABASE" 